export const data = [
  {
    name: "Ajo Idea Space",
    is_fine_dining: "FALSE",
    is_old: "TRUE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Uppercrust",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Fish & Co",
    is_fine_dining: "FALSE",
    is_old: "TRUE",
    is_fish: "TRUE",
    is_asian: "FALSE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Kiyoshi",
    is_fine_dining: "TRUE",
    is_old: "TRUE",
    is_fish: "TRUE",
    is_asian: "TRUE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Soi 71",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "TRUE",
    is_asian: "TRUE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Sura",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "TRUE",
    is_experimental: "TRUE",
    is_cheesy: "FALSE",
  },
  {
    name: "Bella Italia",
    is_fine_dining: "FALSE",
    is_old: "TRUE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "FALSE",
    is_cheesy: "TRUE",
  },
  {
    name: "Cero",
    is_fine_dining: "FALSE",
    is_old: "TRUE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Soi 71",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "TRUE",
    is_asian: "TRUE",
    is_experimental: "TRUE",
    is_cheesy: "FALSE",
  },
  {
    name: "Thai Signatures",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "TRUE",
    is_asian: "TRUE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Korean Restaurant Dhaka",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "TRUE",
    is_experimental: "TRUE",
    is_cheesy: "FALSE",
  },
  {
    name: "Rivendell By Gotcha",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "FALSE",
    is_cheesy: "TRUE",
  },
  {
    name: "Fat Emperror",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "TRUE",
    is_asian: "TRUE",
    is_experimental: "TRUE",
    is_cheesy: "FALSE",
  },
  {
    name: "Saltz FIne Seafood",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "TRUE",
    is_asian: "FALSE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Spagetthi Jazz",
    is_fine_dining: "FALSE",
    is_old: "TRUE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Goong The Castle",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "TRUE",
    is_experimental: "TRUE",
    is_cheesy: "FALSE",
  },
  {
    name: "Umai",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "TRUE",
    is_asian: "TRUE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Ruen Busaba",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "TRUE",
    is_experimental: "TRUE",
    is_cheesy: "FALSE",
  },
  {
    name: "Fool's Diner",
    is_fine_dining: "FALSE",
    is_old: "TRUE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Ginza",
    is_fine_dining: "FALSE",
    is_old: "TRUE",
    is_fish: "FALSE",
    is_asian: "TRUE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "North Fish",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "TRUE",
    is_asian: "FALSE",
    is_experimental: "TRUE",
    is_cheesy: "FALSE",
  },
  {
    name: "New Cathay",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "TRUE",
    is_experimental: "TRUE",
    is_cheesy: "FALSE",
  },
  {
    name: "ICHI",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "TRUE",
    is_asian: "TRUE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Shanghai 10",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "TRUE",
    is_experimental: "TRUE",
    is_cheesy: "FALSE",
  },
  {
    name: "Sushi Samurai",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "TRUE",
    is_asian: "TRUE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Evviva Italian Ristorante",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "TRUE",
    is_cheesy: "TRUE",
  },
  {
    name: "Nori",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "TRUE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "OPlay",
    is_fine_dining: "TRUE",
    is_old: "TRUE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "FALSE",
    is_cheesy: "TRUE",
  },
  {
    name: "Oriental Taste",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "TRUE",
    is_experimental: "TRUE",
    is_cheesy: "FALSE",
  },
  {
    name: "Emerald Bakery",
    is_fine_dining: "FALSE",
    is_old: "TRUE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Ole",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "TRUE",
    is_cheesy: "TRUE",
  },
  {
    name: "The Red Chamber",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "TRUE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "China Garden Restaurant",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "TRUE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Raffinato Ristorante Italiano",
    is_fine_dining: "TRUE",
    is_old: "TRUE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "TRUE",
    is_cheesy: "TRUE",
  },
  {
    name: "El Toro Mexican Restaurant",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "TRUE",
    is_cheesy: "TRUE",
  },
  {
    name: "Samdado",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "TRUE",
    is_asian: "TRUE",
    is_experimental: "TRUE",
    is_cheesy: "FALSE",
  },
  {
    name: "Galitos",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "TRUE",
    is_cheesy: "FALSE",
  },
  {
    name: "Bene Bistro",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Hong Bao",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "TRUE",
    is_experimental: "TRUE",
    is_cheesy: "FALSE",
  },
  {
    name: "C'Zar",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "FALSE",
    is_cheesy: "TRUE",
  },
  {
    name: "TERRACO Rooftop Restaurant",
    is_fine_dining: "FALSE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "TRUE",
    is_cheesy: "TRUE",
  },
  {
    name: "Bao",
    is_fine_dining: "FALSE",
    is_old: "TRUE",
    is_fish: "FALSE",
    is_asian: "TRUE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Cielo Rooftop Gulshan",
    is_fine_dining: "FALSE",
    is_old: "TRUE",
    is_fish: "FALSE",
    is_asian: "FALSE",
    is_experimental: "FALSE",
    is_cheesy: "FALSE",
  },
  {
    name: "Laughing Buddha",
    is_fine_dining: "TRUE",
    is_old: "FALSE",
    is_fish: "FALSE",
    is_asian: "TRUE",
    is_experimental: "TRUE",
    is_cheesy: "FALSE",
  },
] as const;
